import { Task, AttendanceRecord, User } from '../types';
import { filterTasksForUser, filterAttendanceForUser } from '../auth/permissions';

/**
 * Generate Excel File for Tasks or Attendance using XLSX library
 */
export async function exportToExcel(
  type: 'tasks' | 'attendance',
  data: Task[] | AttendanceRecord[],
  currentUser: User,
  fileName: string = 'report'
) {
  // Import xlsx dynamically to optimize load times
  const XLSX = await import('xlsx');

  let rows: Record<string, string | number>[] = [];

  if (type === 'tasks') {
    const tasks = filterTasksForUser(data as Task[], currentUser);
    rows = tasks.map((t) => ({
      'Task Title': t.title,
      Client: t.clientName,
      Assignee: t.assigneeName,
      Status: t.status,
      Priority: t.priority,
      'Due Date': t.dueDate,
      'Completion Date': t.completedAt || 'N/A',
      'Created Date': t.createdAt,
    }));
  } else {
    const attendance = filterAttendanceForUser(data as AttendanceRecord[], currentUser);
    rows = attendance.map((a) => ({
      Employee: a.employeeName,
      Department: a.department,
      Date: a.date,
      Status: a.status,
      'Check In': a.checkIn || '-',
      'Check Out': a.checkOut || '-',
      'Work Hours': a.workHours || 0,
    }));
  }

  const worksheet = XLSX.utils.json_to_sheet(rows);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, type === 'tasks' ? 'Tasks' : 'Attendance');

  XLSX.writeFile(workbook, `${fileName}_${new Date().toISOString().split('T')[0]}.xlsx`);
}

/**
 * Generate PDF File for Tasks or Attendance using jsPDF
 */
export async function exportToPDF(
  type: 'tasks' | 'attendance',
  data: Task[] | AttendanceRecord[],
  currentUser: User,
  fileName: string = 'report'
) {
  const { jsPDF } = await import('jspdf');
  const autoTable = (await import('jspdf-autotable')).default;

  const doc = new jsPDF({ orientation: 'landscape' });

  // Header Title
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59); // Slate-800
  const title = type === 'tasks' ? 'RMH CRM - Tasks Summary Report' : 'RMH CRM - Attendance Report';
  doc.text(title, 14, 16);

  // Subheader info
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated by: ${currentUser.name} (${currentUser.role}) | Date: ${new Date().toLocaleDateString()}`, 14, 23);

  if (type === 'tasks') {
    const tasks = filterTasksForUser(data as Task[], currentUser);
    const tableHeaders = [['Task Title', 'Client', 'Assignee', 'Status', 'Priority', 'Due Date', 'Completed']];
    const tableData = tasks.map((t) => [
      t.title,
      t.clientName,
      t.assigneeName,
      t.status,
      t.priority,
      t.dueDate,
      t.completedAt || '-',
    ]);

    autoTable(doc, {
      startY: 28,
      head: tableHeaders,
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: 255 }, // Dark navy header
      styles: { fontSize: 9, cellPadding: 3 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });
  } else {
    const attendance = filterAttendanceForUser(data as AttendanceRecord[], currentUser);
    const tableHeaders = [['Employee', 'Department', 'Date', 'Status', 'Check In', 'Check Out', 'Hours']];
    const tableData = attendance.map((a) => [
      a.employeeName,
      a.department,
      a.date,
      a.status,
      a.checkIn || '-',
      a.checkOut || '-',
      a.workHours ? `${a.workHours} hrs` : '-',
    ]);

    autoTable(doc, {
      startY: 28,
      head: tableHeaders,
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });
  }

  doc.save(`${fileName}_${new Date().toISOString().split('T')[0]}.pdf`);
}
